import type { ProjectState } from '../types';
import { scaleToGrams, calculateMaterialsCost, calculateMachineCost, calculateLaborCost, calculateTotalCost } from './costCalculator';
import { formatCurrency } from './formatters';

export async function copySummaryToClipboard(state: ProjectState): Promise<void> {
  const grams = scaleToGrams(state.scale, state.customScaleGrams);
  const materials = calculateMaterialsCost(
    state.parsedAminoAcids,
    state.resinCostPerGram,
    grams,
    state.customMaterials,
    state.otherMaterials,
  );
  const totalMaterials = materials.totalMaterialsCost * state.batchCount;
  const machines = calculateMachineCost(state.machines, state.batchCount);
  const labor = calculateLaborCost(state.laborRoles, state.batchCount);
  const totals = calculateTotalCost(
    totalMaterials,
    machines.totalMachineCost,
    labor.totalLaborCost,
    state.batchCount,
    grams,
  );

  const lines = [
    `PeptiPlan - Project Cost Summary`,
    `================================`,
    `Project: ${state.projectName || 'Untitled'}`,
    `Sequence: ${state.sequence || 'N/A'} (${state.parsedAminoAcids.reduce((s, a) => s + a.count, 0)} residues)`,
    `Batches: ${state.batchCount} x ${state.scale}`,
    ``,
    `--- Cost Breakdown ---`,
    `Raw Materials:  ${formatCurrency(totalMaterials)}`,
    `  Amino Acids:  ${formatCurrency(materials.aaCost * state.batchCount)}`,
    `  Coupling:     ${formatCurrency(materials.couplingCost * state.batchCount)}`,
    `  Resin:        ${formatCurrency(materials.resinCost * state.batchCount)}`,
    `  Custom:       ${formatCurrency(materials.customCost * state.batchCount)}`,
    `  Other Mat.:   ${formatCurrency(materials.otherMaterialsCost * state.batchCount)}`,
    `Equipment:      ${formatCurrency(machines.totalMachineCost)}`,
    `Labor:          ${formatCurrency(labor.totalLaborCost)}`,
    ``,
    `--- Totals ---`,
    `Total Cost:     ${formatCurrency(totals.totalCost)}`,
    `Cost per Batch: ${formatCurrency(totals.costPerBatch)}`,
    `Cost per Gram:  ${formatCurrency(totals.costPerGram)}`,
    ``,
    `Generated by PeptiPlan on ${new Date().toLocaleDateString()}`,
  ];

  await navigator.clipboard.writeText(lines.join('\n'));
}
