import type { ProjectState } from '../types';
import {
  scaleToGrams,
  calculateCumulativeYield,
  calculateMaterialsCost,
  calculateMachineCost,
  calculateLaborCost,
  calculateTotalCost,
} from './costCalculator';
import { formatCurrency } from './formatters';

export async function copySummaryToClipboard(state: ProjectState): Promise<void> {
  const grams = scaleToGrams(state.scale, state.customScaleGrams);
  const cumulativeYield = calculateCumulativeYield(state.phases);
  const ptmCostPerBatch = state.ptmModifications.reduce((sum, ptm) => sum + ptm.costDelta, 0);

  const materials = calculateMaterialsCost(
    state.parsedAminoAcids,
    state.resinCostPerGram,
    grams,
    state.customMaterials,
    state.otherMaterials,
    ptmCostPerBatch,
  );
  const totalMaterials = materials.totalMaterialsCost * state.batchCount;
  const machines = calculateMachineCost(state.machines, state.batchCount);
  const labor = calculateLaborCost(state.laborRoles, state.batchCount, state.gmpStatus);
  const totals = calculateTotalCost(
    totalMaterials,
    machines.totalMachineCost,
    labor.totalLaborCost,
    state.batchCount,
    grams,
    cumulativeYield,
  );

  const lines = [
    `PeptiPlan - Project Cost Summary`,
    `================================`,
    `Project: ${state.projectName || 'Untitled'}`,
    `GMP: ${state.gmpStatus === 'gmp' ? 'Yes (+15% labor overhead)' : 'No'}`,
    `Sequence: ${state.sequence || 'N/A'} (${state.parsedAminoAcids.reduce((s, a) => s + a.count, 0)} residues)`,
    `Batches: ${state.batchCount} x ${state.scale}`,
    `Cumulative Yield: ${(cumulativeYield * 100).toFixed(1)}% → ${totals.deliverableGrams.toFixed(2)}g deliverable/batch`,
    state.ptmModifications.length > 0
      ? `PTMs: ${state.ptmModifications.map(p => p.name).join(', ')}`
      : '',
    ``,
    `--- Cost Breakdown ---`,
    `Raw Materials:  ${formatCurrency(totalMaterials)}`,
    `  Amino Acids:  ${formatCurrency(materials.aaCost * state.batchCount)}`,
    `  Coupling:     ${formatCurrency(materials.couplingCost * state.batchCount)}`,
    `  Resin:        ${formatCurrency(materials.resinCost * state.batchCount)}`,
    `  Custom:       ${formatCurrency(materials.customCost * state.batchCount)}`,
    `  Other Mat.:   ${formatCurrency(materials.otherMaterialsCost * state.batchCount)}`,
    materials.ptmCost > 0 ? `  PTMs:         ${formatCurrency(materials.ptmCost * state.batchCount)}` : '',
    `Equipment:      ${formatCurrency(machines.totalMachineCost)}`,
    `Labor:          ${formatCurrency(labor.totalLaborCost)}`,
    labor.gmpOverheadCost > 0 ? `  GMP Overhead: ${formatCurrency(labor.gmpOverheadCost)}` : '',
    ``,
    `--- Totals ---`,
    `Total Cost:     ${formatCurrency(totals.totalCost)}`,
    `Cost per Batch: ${formatCurrency(totals.costPerBatch)}`,
    `Cost per Gram:  ${formatCurrency(totals.costPerGram)} (on deliverable product)`,
    ``,
    `Generated by PeptiPlan on ${new Date().toLocaleDateString()}`,
  ].filter(Boolean);

  await navigator.clipboard.writeText(lines.join('\n'));
}
